export { default as Home } from './HomeScreen'
export { default as Product } from './ProductScreen'
export { default as Cart } from './CartScreen'
export { default as Login } from './LoginScreen'
export { default as Register } from './RegisterScreen'